/* The menu's faces (pet_menu_font.c, SIL OFL 1.1), icons and boot mark
 * (pet_menu_icons.c), generated by firmware/tools/make_menu_assets.py. */
#pragma once

#include "lvgl.h"

extern const lv_font_t pet_menu_font_12;
extern const lv_font_t pet_menu_font_16;
extern const lv_font_t pet_menu_font_20;
extern const lv_font_t pet_menu_font_28;
/* The fonts' copyright notice and SIL OFL 1.1 text, verbatim. */
extern const char pet_menu_font_license[];

extern const lv_image_dsc_t pet_icon_wifi;
extern const lv_image_dsc_t pet_icon_speaker;
extern const lv_image_dsc_t pet_icon_sun;
extern const lv_image_dsc_t pet_icon_mic;
extern const lv_image_dsc_t pet_icon_paw;
extern const lv_image_dsc_t pet_icon_sync;
extern const lv_image_dsc_t pet_icon_power;
extern const lv_image_dsc_t pet_icon_chevron_right;
extern const lv_image_dsc_t pet_icon_chevron_up;
/* The boot page's mark, an 8-bit mask the page tints. */
extern const lv_image_dsc_t pet_boot_mark;
